language: node_js
node_js:
  - node
cache:
  directories:
    - node_modules
install:
  - npm install
before_script:
  - npm run lint
  - npm run test -- --passWithNoTests --coverage
script:
  - npm run build
before_deploy:
  - cp README.md dist/
  - if [ $CNAME ]; then
    echo $CNAME > dist/CNAME;
    fi
deploy:
  - provider: pages
    github_token: $GITHUB_TOKEN
    skip-cleanup: true
    keep-history: false
    local-dir: dist
    on:
      branch: master
      condition: $GITHUB_TOKEN
